### ISSUE TITLE
TLMGR Update Fails

### ISSUE THREAD

**Issue by LinusDietz** [Strauman/latex-docker#7] opened 2019-05-03 13:40 UTC
Hi,
seems like the container just stopped working today. Specifically, TLMGR does not update anymore.

```
tlmgr: Remote repository is newer than local (2018 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
```

Cheers,
Linus

**Comment by Strauman** [comment] 2019-05-03 14:38
Thanks for letting me know. I'm working on this as we speak! Should be fixed soon!

**Comment by Strauman** [comment] 2019-05-03 15:47
@LinusDietz -- It appears that the problem is fixed for the `small` scheme. The others will likely follow. Please reopen this issue if it does not work as expected :)

**Closed as completed by Strauman** 2019-05-03 15:47 UTC
